### ISSUE TITLE
JOS - Scroll RootMargin Update 

### ISSUE THREAD

**Issue by jesvijonathan** [ElvinEga/kazifi_landing_preview#1]
Hello @ElvinEga,

Firstly Awesome work !

I just wanted to suggest adding a rootMargin value to set a scroll trigger area.

```js
onload = () => {
  const options = {
    debugMode: true,
    animation: "flip",
    duration: 0.7,
    rootMargin: "0% 0% 40% 0%",  // Set bottom rootMargin to 40%
  };
  JOS.init(options);
  //JOS.version();
};
```

So yeah :
```js
rootMargin: "0% 0% 40% 0%",    // top | right | bottom | left
```

This way, you can have the elements animate after they are 40% into the screen area. You can mess around with the values though...

Love your work !

**Comment by jesvijonathan** [comment]
Sry, duplicate issue...

Issue moved here #2

**Comment by ElvinEga** [comment]
Thank you I will implement that
